version: 2

workingDirectory: &workingDirectory /usr/src/app

# defaultImage: &defaultImage
  docker:
    - image: node:8.10 # Keep in sync with dockerfile image
  working_directory: *workingDirectory

jobs:
  deploy:
    docker:
        - image: node:8.10 # Keep in sync with dockerfile image
    working_directory: *workingDirectory
    steps:
      - run:
          name: Deploy
          command: aws s3 sync public/html s3://daicogen.com --delete

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master