version: 2

workingDirectory: &workingDirectory /usr/src/app

jobs:
  deploy:
    docker:
        - image: mesosphere/aws-cli:latest
    working_directory: *workingDirectory
    steps:
      - checkout
      - run:
          name: Deploy
          command: aws s3 sync public/html s3://daicogen.com --delete

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master