-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Campaign exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Campaign
selection constructor =
    Object.selection constructor


id : Field Float Api.Object.Campaign
id =
    Object.fieldDecoder "id" [] Decode.float


creator : Field String Api.Object.Campaign
creator =
    Object.fieldDecoder "creator" [] Decode.string


category : Field String Api.Object.Campaign
category =
    Object.fieldDecoder "category" [] Decode.string


project_title : Field String Api.Object.Campaign
project_title =
    Object.fieldDecoder "project_title" [] Decode.string


description : Field String Api.Object.Campaign
description =
    Object.fieldDecoder "description" [] Decode.string


image : Field String Api.Object.Campaign
image =
    Object.fieldDecoder "image" [] Decode.string


funding_goal : Field Float Api.Object.Campaign
funding_goal =
    Object.fieldDecoder "funding_goal" [] Decode.float


campaign_start : Field Float Api.Object.Campaign
campaign_start =
    Object.fieldDecoder "campaign_start" [] Decode.float


campaign_end : Field Float Api.Object.Campaign
campaign_end =
    Object.fieldDecoder "campaign_end" [] Decode.float


title : Field String Api.Object.Campaign
title =
    Object.fieldDecoder "title" [] Decode.string


pledge_amount : Field Float Api.Object.Campaign
pledge_amount =
    Object.fieldDecoder "pledge_amount" [] Decode.float


reward_description : Field String Api.Object.Campaign
reward_description =
    Object.fieldDecoder "reward_description" [] Decode.string


estimated_delivery : Field Float Api.Object.Campaign
estimated_delivery =
    Object.fieldDecoder "estimated_delivery" [] Decode.float


projectTitle : Field String Api.Object.Campaign
projectTitle =
    Object.fieldDecoder "projectTitle" [] Decode.string


fundingGoal : Field Float Api.Object.Campaign
fundingGoal =
    Object.fieldDecoder "fundingGoal" [] Decode.float


campaignStart : Field Float Api.Object.Campaign
campaignStart =
    Object.fieldDecoder "campaignStart" [] Decode.float


campaignEnd : Field Float Api.Object.Campaign
campaignEnd =
    Object.fieldDecoder "campaignEnd" [] Decode.float


pledgeAmount : Field Float Api.Object.Campaign
pledgeAmount =
    Object.fieldDecoder "pledgeAmount" [] Decode.float


rewardDescription : Field String Api.Object.Campaign
rewardDescription =
    Object.fieldDecoder "rewardDescription" [] Decode.string


estimatedDelivery : Field Float Api.Object.Campaign
estimatedDelivery =
    Object.fieldDecoder "estimatedDelivery" [] Decode.float
