-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Poll exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Poll
selection constructor =
    Object.selection constructor


proposal : Field String Api.Object.Poll
proposal =
    Object.fieldDecoder "proposal" [] Decode.string


yesvotes : Field Float Api.Object.Poll
yesvotes =
    Object.fieldDecoder "yesvotes" [] Decode.float


novotes : Field Float Api.Object.Poll
novotes =
    Object.fieldDecoder "novotes" [] Decode.float


icocreator : Field String Api.Object.Poll
icocreator =
    Object.fieldDecoder "icocreator" [] Decode.string


votes : SelectionSet decodesTo Api.Object.Vote -> Field (List decodesTo) Api.Object.Poll
votes object =
    Object.selectionField "votes" [] object (identity >> Decode.list)


voteProposals : SelectionSet decodesTo Api.Object.VoteProposal -> Field (List decodesTo) Api.Object.Poll
voteProposals object =
    Object.selectionField "voteProposals" [] object (identity >> Decode.list)
