-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.TokenSale exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.TokenSale
selection constructor =
    Object.selection constructor


name : Field String Api.Object.TokenSale
name =
    Object.fieldDecoder "name" [] Decode.string


symbol : Field String Api.Object.TokenSale
symbol =
    Object.fieldDecoder "symbol" [] Decode.string


supply : Field Float Api.Object.TokenSale
supply =
    Object.fieldDecoder "supply" [] Decode.float


allocation : Field Float Api.Object.TokenSale
allocation =
    Object.fieldDecoder "allocation" [] Decode.float


value : Field Float Api.Object.TokenSale
value =
    Object.fieldDecoder "value" [] Decode.float


softcap : Field Float Api.Object.TokenSale
softcap =
    Object.fieldDecoder "softcap" [] Decode.float


hardcap : Field Float Api.Object.TokenSale
hardcap =
    Object.fieldDecoder "hardcap" [] Decode.float


startDate : Field Float Api.Object.TokenSale
startDate =
    Object.fieldDecoder "startDate" [] Decode.float


endDate : Field Float Api.Object.TokenSale
endDate =
    Object.fieldDecoder "endDate" [] Decode.float
