-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Vote exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Vote
selection constructor =
    Object.selection constructor


iconame : Field String Api.Object.Vote
iconame =
    Object.fieldDecoder "iconame" [] Decode.string


idvoter : Field String Api.Object.Vote
idvoter =
    Object.fieldDecoder "idvoter" [] Decode.string


trvoter : Field String Api.Object.Vote
trvoter =
    Object.fieldDecoder "trvoter" [] Decode.string


pick : Field Bool Api.Object.Vote
pick =
    Object.fieldDecoder "pick" [] Decode.bool
