-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object exposing (..)


type Poll
    = Poll


type Project
    = Project


type TokenSale
    = TokenSale


type Vote
    = Vote


type VoteProposal
    = VoteProposal
